# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-07 23:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='first_slide_button_text',
            field=models.CharField(default='About EPC', max_length=70),
        ),
        migrations.AddField(
            model_name='homepage',
            name='first_slide_scripture',
            field=models.TextField(default='Scriptures'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='first_slide_title',
            field=models.TextField(default='Welcome To EPC'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='first_slide_verse',
            field=models.CharField(default='Matthew 28:10-20', max_length=100),
        ),
        migrations.AddField(
            model_name='homepage',
            name='fourth_slide_button_text',
            field=models.CharField(default='About EPC', max_length=70),
        ),
        migrations.AddField(
            model_name='homepage',
            name='fourth_slide_scripture',
            field=models.TextField(default='Scriptures'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='fourth_slide_title',
            field=models.TextField(default='Welcome To EPC'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='fourth_slide_verse',
            field=models.CharField(default='Matthew 28:10-20', max_length=100),
        ),
        migrations.AddField(
            model_name='homepage',
            name='second_slide_button_text',
            field=models.CharField(default='About EPC', max_length=70),
        ),
        migrations.AddField(
            model_name='homepage',
            name='second_slide_scripture',
            field=models.TextField(default='Scriptures'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='second_slide_title',
            field=models.TextField(default='Welcome To EPC'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='second_slide_verse',
            field=models.CharField(default='Matthew 28:10-20', max_length=100),
        ),
        migrations.AddField(
            model_name='homepage',
            name='third_slide_button_text',
            field=models.CharField(default='About EPC', max_length=70),
        ),
        migrations.AddField(
            model_name='homepage',
            name='third_slide_scripture',
            field=models.TextField(default='Scriptures'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='third_slide_title',
            field=models.TextField(default='Welcome To EPC'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='third_slide_verse',
            field=models.CharField(default='Matthew 28:10-20', max_length=100),
        ),
    ]
