# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-07 23:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20170607_2333'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='first_slide_button_link',
            field=models.CharField(default='/about/', max_length=70),
        ),
        migrations.AddField(
            model_name='homepage',
            name='fourth_slide_button_link',
            field=models.CharField(default='/about/', max_length=70),
        ),
        migrations.AddField(
            model_name='homepage',
            name='second_slide_button_link',
            field=models.CharField(default='/about/', max_length=70),
        ),
        migrations.AddField(
            model_name='homepage',
            name='third_slide_button_link',
            field=models.CharField(default='/about/', max_length=70),
        ),
    ]
