# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-08 18:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0019_delete_filter'),
        ('home', '0003_auto_20170607_2353'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='confession_main_title',
            field=models.CharField(default='Our Confession', max_length=80),
        ),
        migrations.AddField(
            model_name='homepage',
            name='fifth_confession_icon',
            field=models.ForeignKey(help_text='64x64 icon', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='fifth_confession_scripture',
            field=models.TextField(default='Scripture'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='fifth_confession_title',
            field=models.CharField(default='fifth confession', max_length=80),
        ),
        migrations.AddField(
            model_name='homepage',
            name='fifth_confession_verse',
            field=models.CharField(default='Mathew 1:18', max_length=50),
        ),
        migrations.AddField(
            model_name='homepage',
            name='first_confession_icon',
            field=models.ForeignKey(help_text='64x64 icon', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='first_confession_scripture',
            field=models.TextField(default='Scripture'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='first_confession_title',
            field=models.CharField(default='first confession', max_length=80),
        ),
        migrations.AddField(
            model_name='homepage',
            name='first_confession_verse',
            field=models.CharField(default='Mathew 1:18', max_length=50),
        ),
        migrations.AddField(
            model_name='homepage',
            name='fourth_confession_icon',
            field=models.ForeignKey(help_text='64x64 icon', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='fourth_confession_scripture',
            field=models.TextField(default='Scripture'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='fourth_confession_title',
            field=models.CharField(default='fourth confession', max_length=80),
        ),
        migrations.AddField(
            model_name='homepage',
            name='fourth_confession_verse',
            field=models.CharField(default='Mathew 1:18', max_length=50),
        ),
        migrations.AddField(
            model_name='homepage',
            name='second_confession_icon',
            field=models.ForeignKey(help_text='64x64 icon', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='second_confession_scripture',
            field=models.TextField(default='Scripture'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='second_confession_title',
            field=models.CharField(default='second confession', max_length=80),
        ),
        migrations.AddField(
            model_name='homepage',
            name='second_confession_verse',
            field=models.CharField(default='Mathew 1:18', max_length=50),
        ),
        migrations.AddField(
            model_name='homepage',
            name='third_confession_icon',
            field=models.ForeignKey(help_text='64x64 icon', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='third_confession_scripture',
            field=models.TextField(default='Scripture'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='third_confession_title',
            field=models.CharField(default='third confession', max_length=80),
        ),
        migrations.AddField(
            model_name='homepage',
            name='third_confession_verse',
            field=models.CharField(default='Mathew 1:18', max_length=50),
        ),
    ]
