# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-08 23:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20170608_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='sermon_video_button_link',
            field=models.CharField(default='/watch', max_length=80),
        ),
        migrations.AddField(
            model_name='homepage',
            name='sermon_video_button_text',
            field=models.CharField(default='Watch more', max_length=30),
        ),
        migrations.AddField(
            model_name='homepage',
            name='sermon_video_description',
            field=models.TextField(default='Click play to watch video'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='sermon_video_main_title',
            field=models.CharField(default='Sermon Video', max_length=80),
        ),
        migrations.AddField(
            model_name='homepage',
            name='sermon_video_subtitle',
            field=models.CharField(default='Recent Sermon Video', max_length=80),
        ),
    ]
