# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-09 17:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0019_delete_filter'),
        ('home', '0005_auto_20170608_2349'),
    ]

    operations = [
        migrations.CreateModel(
            name='SermonVideos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sermon_day', models.CharField(default="Lord's Day", max_length=50)),
                ('sermon_title', models.TextField(default='Sermon Title')),
                ('sermon_date', models.CharField(default='May 23 2017', max_length=50)),
                ('sermon_chapter', models.CharField(default='Act 22:1-2', max_length=80)),
                ('sermon_link', models.TextField(default='www.youtube.com')),
                ('sermon_share_code', models.CharField(default='LHJowUFSKMA', max_length=80)),
                ('sermon_thumbnail_image', models.ForeignKey(help_text='Sermon Thumbnail Image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
            ],
        ),
    ]
