# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-09 17:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20170609_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='sermonvideo',
            name='upload_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
