# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-09 22:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_remove_sermonvideo_sermon_day'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SermonDay',
        ),
    ]
