# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-09 22:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_delete_sermonday'),
    ]

    operations = [
        migrations.CreateModel(
            name='SermonDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sermon_day', models.CharField(default="Lord's Day", max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='sermonvideo',
            name='sermon_day',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.SermonDay'),
        ),
    ]
