# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-12 18:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0033_remove_golive_expiry_help_text'),
        ('wagtailimages', '0019_delete_filter'),
        ('home', '0012_auto_20170609_2252'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(default='Pastor Kim', max_length=30)),
                ('author_title', models.CharField(default='Eastern Church Senior Pastor', max_length=60)),
                ('author_image', models.ForeignKey(help_text='75x75 pixel', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
            ],
        ),
        migrations.CreateModel(
            name='BlogPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('blog_title', models.TextField(default='Blog Title')),
                ('blog_date', models.DateTimeField(auto_now_add=True)),
                ('blog_content', wagtail.wagtailcore.fields.RichTextField()),
                ('blog_button_text', models.CharField(default='Read more blog', max_length=50)),
                ('blog_author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.Author')),
                ('blog_button_link', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page')),
                ('blog_image', models.ForeignKey(help_text='Blog Image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AddField(
            model_name='homepage',
            name='blog_button_link',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='blog_button_text',
            field=models.CharField(default='See more blogs', max_length=50),
        ),
        migrations.AddField(
            model_name='homepage',
            name='blog_description',
            field=models.TextField(default='Description for blog section'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='blog_main_title',
            field=models.CharField(default='Blog', max_length=80),
        ),
        migrations.AddField(
            model_name='homepage',
            name='blog_subtitle',
            field=models.CharField(default='Message from pastor', max_length=100),
        ),
    ]
