# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-12 20:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20170612_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogindexpage',
            name='blog_featured_name',
            field=models.CharField(default='Featured Blog', max_length=100),
        ),
    ]
