# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-12 21:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0019_delete_filter'),
        ('wagtailcore', '0033_remove_golive_expiry_help_text'),
        ('home', '0015_blogindexpage_blog_featured_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedBlogPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('blog_title', models.TextField(default='Blog Title')),
                ('blog_date', models.DateTimeField(auto_now_add=True)),
                ('blog_content', wagtail.core.fields.RichTextField()),
                ('blog_button_text', models.CharField(default='Read more blog', max_length=50)),
                ('blog_author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.Author')),
                ('blog_button_link', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page')),
                ('blog_image', models.ForeignKey(help_text='Blog Image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.RemoveField(
            model_name='blogpage',
            name='blog_featured',
        ),
    ]
