# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-12 22:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0033_remove_golive_expiry_help_text'),
        ('wagtailforms', '0003_capitalizeverbose'),
        ('wagtailredirects', '0005_capitalizeverbose'),
        ('home', '0016_auto_20170612_2153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='featuredblogpage',
            name='blog_author',
        ),
        migrations.RemoveField(
            model_name='featuredblogpage',
            name='blog_button_link',
        ),
        migrations.RemoveField(
            model_name='featuredblogpage',
            name='blog_image',
        ),
        migrations.RemoveField(
            model_name='featuredblogpage',
            name='page_ptr',
        ),
        migrations.AddField(
            model_name='blogpage',
            name='blog_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='FeaturedBlogPage',
        ),
    ]
