# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-12 23:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_auto_20170612_2247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpage',
            name='blog_featured',
        ),
    ]
