# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-13 16:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_eventindexpage_featuredevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegularEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_title', models.CharField(default='Event Title', max_length=50)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('event_date', models.CharField(default='6월 23일', max_length=20)),
                ('event_time', models.CharField(default='11:00 AM', max_length=20)),
                ('event_description', models.TextField(default='Event Description', max_length=150)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
