# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-13 17:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0019_delete_filter'),
        ('wagtailcore', '0033_remove_golive_expiry_help_text'),
        ('home', '0021_auto_20170613_1627'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ContactPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='DonationPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='EducationPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='KidsPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='MissionPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='SermonPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='YoungAdultPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='YouthGroupPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AddField(
            model_name='homepage',
            name='contact_card_button_link',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='contact_card_button_text',
            field=models.CharField(default='Learn more', max_length=10),
        ),
        migrations.AddField(
            model_name='homepage',
            name='contact_card_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='contact_card_subtitle',
            field=models.CharField(default='Keep in touch with us', max_length=50),
        ),
        migrations.AddField(
            model_name='homepage',
            name='contact_card_title',
            field=models.CharField(default='Contact', max_length=10),
        ),
        migrations.AddField(
            model_name='homepage',
            name='education_card_button_link',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='education_card_button_text',
            field=models.CharField(default='Learn more', max_length=10),
        ),
        migrations.AddField(
            model_name='homepage',
            name='education_card_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='education_card_subtitle',
            field=models.CharField(default='Nicaragua', max_length=50),
        ),
        migrations.AddField(
            model_name='homepage',
            name='education_card_title',
            field=models.CharField(default='Mission', max_length=10),
        ),
        migrations.AddField(
            model_name='homepage',
            name='mission_card_button_link',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='mission_card_button_text',
            field=models.CharField(default='Learn more', max_length=10),
        ),
        migrations.AddField(
            model_name='homepage',
            name='mission_card_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='mission_card_subtitle',
            field=models.CharField(default='Nicaragua', max_length=50),
        ),
        migrations.AddField(
            model_name='homepage',
            name='mission_card_title',
            field=models.CharField(default='Mission', max_length=10),
        ),
        migrations.AddField(
            model_name='homepage',
            name='mission_main_title',
            field=models.CharField(default='EPC Mission', max_length=50),
        ),
        migrations.AddField(
            model_name='homepage',
            name='mission_scripture',
            field=models.TextField(default='Scripture for mission section'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='mission_verse',
            field=models.CharField(default='Hebrew 10:25', max_length=50),
        ),
        migrations.AddField(
            model_name='homepage',
            name='offering_card_button_link',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='offering_card_button_text',
            field=models.CharField(default='Learn more', max_length=10),
        ),
        migrations.AddField(
            model_name='homepage',
            name='offering_card_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='offering_card_subtitle',
            field=models.CharField(default='Nicaragua', max_length=50),
        ),
        migrations.AddField(
            model_name='homepage',
            name='offering_card_title',
            field=models.CharField(default='Mission', max_length=10),
        ),
        migrations.AddField(
            model_name='homepage',
            name='service_button_link',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='service_button_text',
            field=models.CharField(default='See more Service info', max_length=50),
        ),
        migrations.AddField(
            model_name='homepage',
            name='service_friday_day',
            field=models.CharField(default='Friday Day', max_length=20),
        ),
        migrations.AddField(
            model_name='homepage',
            name='service_friday_day_schedule',
            field=models.CharField(default='7:30 PM', max_length=20),
        ),
        migrations.AddField(
            model_name='homepage',
            name='service_hero_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='service_lord_day',
            field=models.CharField(default="Lord's Day", max_length=50),
        ),
        migrations.AddField(
            model_name='homepage',
            name='service_lord_day_schedule_1',
            field=models.CharField(default='5:30 AM', max_length=20),
        ),
        migrations.AddField(
            model_name='homepage',
            name='service_lord_day_schedule_2',
            field=models.CharField(default='9:30 AM', max_length=20),
        ),
        migrations.AddField(
            model_name='homepage',
            name='service_lord_day_schedule_3',
            field=models.CharField(default='11:00 AM', max_length=20),
        ),
        migrations.AddField(
            model_name='homepage',
            name='service_lord_day_schedule_4',
            field=models.CharField(default='2:00 PM', max_length=20),
        ),
        migrations.AddField(
            model_name='homepage',
            name='service_scripture',
            field=models.TextField(default='Scripture for EPC service section'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='service_subtitle',
            field=models.CharField(default='Service Schedule', max_length=50),
        ),
        migrations.AddField(
            model_name='homepage',
            name='service_title',
            field=models.CharField(default='EPC Worship Service', max_length=50),
        ),
        migrations.AddField(
            model_name='homepage',
            name='service_verse',
            field=models.CharField(default='Hebrew 10:25', max_length=50),
        ),
    ]
