# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-13 17:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_auto_20170613_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='contact_card_subtitle',
            field=models.CharField(default='Keep in touch with us', max_length=50),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='education_card_subtitle',
            field=models.CharField(default='Korean School and TIU', max_length=50),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='education_card_title',
            field=models.CharField(default='Education', max_length=10),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='mission_card_subtitle',
            field=models.CharField(default='Nicaragua', max_length=50),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='offering_card_subtitle',
            field=models.CharField(default='Offering & Donation', max_length=50),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='offering_card_title',
            field=models.CharField(default='Offering', max_length=10),
        ),
    ]
