# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-13 17:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_auto_20170613_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='contact_card_title',
            field=models.CharField(default='Contact', max_length=30),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='education_card_title',
            field=models.CharField(default='Education', max_length=30),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='mission_card_title',
            field=models.CharField(default='Mission', max_length=30),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='mission_main_title',
            field=models.CharField(default='EPC Mission', max_length=50),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='offering_card_title',
            field=models.CharField(default='Offering', max_length=30),
        ),
    ]
