# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-13 17:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_auto_20170613_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='service_button_text',
            field=models.CharField(default='See more Service info', max_length=50),
        ),
    ]
