# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-13 22:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0036_auto_20170613_2231'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactpage',
            name='address_1',
            field=models.CharField(default='4270 W 6th St', max_length=50),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='address_2',
            field=models.CharField(default='Los Angeles, CA 90020', max_length=50),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='address_title',
            field=models.CharField(default='교회 주소', max_length=30),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='contact_form_title',
            field=models.TextField(default='문의 사항이 있으시면 아래 폼을 작성해서 보내기를 눌러주세요'),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='contact_hero_subtitle',
            field=models.TextField(default='교회와 사역에 질문이 있으시면 아래 연락방법으로 연락하시길 바랍니다.'),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='contact_hero_title',
            field=models.CharField(default='모든 분들의 연락을 기다립니다.', max_length=100),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='email_address',
            field=models.CharField(default='이메일 : info@epcla.org', max_length=50),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='email_title',
            field=models.CharField(default='이메일 주소', max_length=30),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='fax_number',
            field=models.CharField(default='팩스: (213)383-9467', max_length=50),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='phone_number',
            field=models.CharField(default='사무실 : (213)383-3261', max_length=50),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='phone_title',
            field=models.CharField(default='전화번호', max_length=30),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='service_schedule_1',
            field=models.CharField(default='주일 예배: 9:30 am / 11:00 am / 2:00 pm', max_length=80),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='service_schedule_2',
            field=models.CharField(default='금요예배 : 7:30 pm', max_length=80),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='service_title',
            field=models.CharField(default='예배 시간', max_length=30),
        ),
    ]
