# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-13 23:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0033_remove_golive_expiry_help_text'),
        ('wagtailforms', '0003_capitalizeverbose'),
        ('wagtailredirects', '0005_capitalizeverbose'),
        ('home', '0037_auto_20170613_2248'),
    ]

    operations = [
        migrations.CreateModel(
            name='GivePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('give_hero_title', models.TextField(default='구제를 좋아하는 자는 풍족하여질 것이요 남을 윤택하게 하는 자는 윤택하여지리라')),
                ('give_verse', models.CharField(default='잠언 11장 25절', max_length=30)),
                ('offering_title', models.CharField(default='연보', max_length=20)),
                ('offering_subtitle', models.CharField(default='십일조 / 주일연보/ 감사연보', max_length=80)),
                ('mission_title', models.CharField(default='선교 헌금', max_length=20)),
                ('mission_subtitle', models.CharField(default='니카라과를 위한 선교 헌금', max_length=80)),
                ('mission_button_text', models.CharField(default='선교 정보 더보기', max_length=40)),
                ('education_title', models.CharField(default='교육 후원', max_length=20)),
                ('education_subtitle', models.CharField(default='한국학교 및 틴데일 신학교 후원', max_length=80)),
                ('education_button_text', models.CharField(default='교육 기관 더 보기', max_length=40)),
                ('donation_title', models.CharField(default='일반 후원', max_length=20)),
                ('donation_subtitle', models.CharField(default='고아와 과부, 가정형편이 어려운분들을 위한 후원', max_length=80)),
                ('give_main_title', models.CharField(default='후원 방법', max_length=30)),
                ('check_subtitle', models.CharField(default='개인 체크(check)으로 후원', max_length=80)),
                ('check_title', models.CharField(default='체크 보내기', max_length=50)),
                ('check_description', wagtail.core.fields.RichTextField(default='description for check donation')),
                ('onetime_subtitle', models.CharField(default='온라인 후원', max_length=80)),
                ('onetime_title', models.CharField(default='일회성 후원', max_length=50)),
                ('onetime_description', wagtail.core.fields.RichTextField(default='description for onetime donation')),
                ('onetime_button_text', models.CharField(default='온라인 후원', max_length=50)),
                ('onetime_button_link', models.CharField(default='www.epcla.com', max_length=50)),
                ('recurring_subtitle', models.CharField(default='온라인 후원', max_length=80)),
                ('recurring_title', models.CharField(default='주기적 후원', max_length=50)),
                ('recurring_description', wagtail.core.fields.RichTextField(default='description for recurring donation')),
                ('recurring_button_text', models.CharField(default='온라인 후원', max_length=50)),
                ('recurring_button_link', models.CharField(default='www.epcla.com', max_length=50)),
                ('education_button_link', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page')),
                ('mission_button_link', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.RemoveField(
            model_name='donationpage',
            name='page_ptr',
        ),
        migrations.DeleteModel(
            name='DonationPage',
        ),
    ]
