# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-14 17:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0033_remove_golive_expiry_help_text'),
        ('wagtailforms', '0003_capitalizeverbose'),
        ('wagtailredirects', '0005_capitalizeverbose'),
        ('home', '0040_contactpage2_formfield2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactpage2',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='formfield2',
            name='page',
        ),
        migrations.DeleteModel(
            name='ContactPage2',
        ),
        migrations.DeleteModel(
            name='FormField2',
        ),
    ]
