# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-14 18:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0019_delete_filter'),
        ('home', '0042_auto_20170614_1832'),
    ]

    operations = [
        migrations.CreateModel(
            name='FridaySermon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sermon_title', models.TextField(default='Sermon Title')),
                ('sermon_date', models.CharField(default='May 23 2017', max_length=50)),
                ('sermon_chapter', models.CharField(default='Act 22:1-2', max_length=80)),
                ('sermon_link', models.TextField(default='www.youtube.com')),
                ('sermon_share_code', models.CharField(default='LHJowUFSKMA', max_length=80)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('sermon_day', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.SermonDay')),
                ('sermon_thumbnail_image', models.ForeignKey(help_text='Sermon Thumbnail Image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LordDaySermon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sermon_title', models.TextField(default='Sermon Title')),
                ('sermon_date', models.CharField(default='May 23 2017', max_length=50)),
                ('sermon_chapter', models.CharField(default='Act 22:1-2', max_length=80)),
                ('sermon_link', models.TextField(default='www.youtube.com')),
                ('sermon_share_code', models.CharField(default='LHJowUFSKMA', max_length=80)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('sermon_day', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.SermonDay')),
                ('sermon_thumbnail_image', models.ForeignKey(help_text='Sermon Thumbnail Image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='sermonvideo',
            name='sermon_day',
        ),
        migrations.RemoveField(
            model_name='sermonvideo',
            name='sermon_thumbnail_image',
        ),
        migrations.DeleteModel(
            name='SermonVideo',
        ),
    ]
