# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-19 17:08
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0043_auto_20170614_1853'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='blogpage',
            managers=[
                ('latest_blogs', django.db.models.manager.Manager()),
            ],
        ),
    ]
