# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-19 17:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0044_auto_20170619_1708'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='blogpage',
            managers=[
            ],
        ),
    ]
