# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-05 20:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0033_remove_golive_expiry_help_text'),
        ('wagtailimages', '0019_delete_filter'),
        ('home', '0045_auto_20170619_1723'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElementaryPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('elem_hero_title', models.CharField(default='동부 교회 초등부', max_length=80)),
                ('elem_hero_verse', models.CharField(default='마태복음 18장 2-3절', max_length=80)),
                ('elem_hero_scripture', models.TextField(default='Scripture for kids page')),
                ('elem_tab_title_1', models.CharField(default='초등부', max_length=30)),
                ('elem_tab_content_title_1', models.CharField(default='초등부', max_length=30)),
                ('elem_tab_content_age', models.CharField(default='0세부터 3세', max_length=50)),
                ('elem_tab_content_info', models.TextField(default='예배 안내: 오전 11:00 23번 방')),
                ('elem_tab_content', wagtail.core.fields.RichTextField(default='Intro to Kinder')),
                ('elem_tab_image_1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
                ('elem_tab_image_2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
                ('elem_tab_image_3', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='NurseryPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('nursery_hero_title', models.CharField(default='동부 교회 영아부', max_length=80)),
                ('nursery_here_verse', models.CharField(default='마태복음 18장 2-3절', max_length=80)),
                ('nursery_hero_scripture', models.TextField(default='Scripture for kids page')),
                ('nursery_tab_title_1', models.CharField(default='영아부', max_length=30)),
                ('nursery_tab_content_title_1', models.CharField(default='영아부', max_length=30)),
                ('nursery_tab_content_age', models.CharField(default='0세부터 3세', max_length=50)),
                ('nursery_tab_content_info', models.TextField(default='예배 안내: 오전 11:00 23번 방')),
                ('nursery_tab_content', wagtail.core.fields.RichTextField(default='Intro to Nursery')),
                ('nursery_tab_image_1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
                ('nursery_tab_image_2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
                ('nursery_tab_image_3', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.RemoveField(
            model_name='kidspage',
            name='elem_tab_content',
        ),
        migrations.RemoveField(
            model_name='kidspage',
            name='elem_tab_content_age',
        ),
        migrations.RemoveField(
            model_name='kidspage',
            name='elem_tab_content_info',
        ),
        migrations.RemoveField(
            model_name='kidspage',
            name='elem_tab_content_title_1',
        ),
        migrations.RemoveField(
            model_name='kidspage',
            name='elem_tab_image_1',
        ),
        migrations.RemoveField(
            model_name='kidspage',
            name='elem_tab_image_2',
        ),
        migrations.RemoveField(
            model_name='kidspage',
            name='elem_tab_image_3',
        ),
        migrations.RemoveField(
            model_name='kidspage',
            name='kids_tab_title_2',
        ),
        migrations.RemoveField(
            model_name='kidspage',
            name='kids_tab_title_3',
        ),
        migrations.RemoveField(
            model_name='kidspage',
            name='nursery_tab_content',
        ),
        migrations.RemoveField(
            model_name='kidspage',
            name='nursery_tab_content_age',
        ),
        migrations.RemoveField(
            model_name='kidspage',
            name='nursery_tab_content_info',
        ),
        migrations.RemoveField(
            model_name='kidspage',
            name='nursery_tab_content_title_1',
        ),
        migrations.RemoveField(
            model_name='kidspage',
            name='nursery_tab_image_1',
        ),
        migrations.RemoveField(
            model_name='kidspage',
            name='nursery_tab_image_2',
        ),
        migrations.RemoveField(
            model_name='kidspage',
            name='nursery_tab_image_3',
        ),
        migrations.RemoveField(
            model_name='youngadultpage',
            name='em_tab_content',
        ),
        migrations.RemoveField(
            model_name='youngadultpage',
            name='em_tab_content_age',
        ),
        migrations.RemoveField(
            model_name='youngadultpage',
            name='em_tab_content_info',
        ),
        migrations.RemoveField(
            model_name='youngadultpage',
            name='em_tab_content_title_1',
        ),
        migrations.RemoveField(
            model_name='youngadultpage',
            name='em_tab_image_1',
        ),
        migrations.RemoveField(
            model_name='youngadultpage',
            name='em_tab_image_2',
        ),
        migrations.RemoveField(
            model_name='youngadultpage',
            name='em_tab_image_3',
        ),
        migrations.AlterField(
            model_name='kidspage',
            name='kids_hero_title',
            field=models.CharField(default='동부 교회 유치부', max_length=80),
        ),
        migrations.AlterField(
            model_name='kidspage',
            name='kids_tab_title_1',
            field=models.CharField(default='유치부', max_length=30),
        ),
        migrations.AlterField(
            model_name='youngadultpage',
            name='ya_hero_title',
            field=models.CharField(default='청년부', max_length=80),
        ),
    ]
