# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-07 21:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0019_delete_filter'),
        ('wagtailcore', '0039_collectionviewrestriction'),
        ('home', '0046_auto_20170705_2059'),
    ]

    operations = [
        migrations.CreateModel(
            name='EMPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('em_hero_title', models.CharField(default='English Ministry', max_length=80)),
                ('em_hero_verse', models.CharField(default='Psalm 119:9-16', max_length=80)),
                ('em_hero_scripture', models.TextField(default='Scripture for English Ministry')),
                ('em_tab_content_title_1', models.CharField(default='English Ministry', max_length=30)),
                ('em_tab_content_age', models.CharField(default='English Ministry.', max_length=50)),
                ('em_tab_content_info', models.TextField(default='예배 안내: 오후 1:00 청년부실')),
                ('em_tab_content', wagtail.core.fields.RichTextField(default='Intro to English Ministry')),
                ('em_tab_image_1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
                ('em_tab_image_2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
                ('em_tab_image_3', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='LordDayAfternoonSermon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sermon_title', models.TextField(default='Sermon Title')),
                ('sermon_date', models.CharField(default='May 23 2017', max_length=50)),
                ('sermon_chapter', models.CharField(default='Act 22:1-2', max_length=80)),
                ('sermon_link', models.TextField(default='www.youtube.com')),
                ('sermon_share_code', models.CharField(default='LHJowUFSKMA', max_length=80)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('sermon_day', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.SermonDay')),
                ('sermon_thumbnail_image', models.ForeignKey(help_text='Sermon Thumbnail Image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LordDayAfternoonSermonField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('hero_title', models.CharField(default='주일 설교 영상', max_length=80)),
                ('hero_subtitle', models.TextField(default='성경을 성경으로 해석한다')),
                ('hero_description', wagtail.core.fields.RichTextField(default='Description')),
                ('sermon_main_title_1', models.CharField(default='최신 주일 예배 설교 영상', max_length=100)),
                ('sermon_main_title_2', models.CharField(default='지난 주일 예배 설교 영상들', max_length=100)),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LordDayAfternoonSermonPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='LordDayMorningSermon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sermon_title', models.TextField(default='Sermon Title')),
                ('sermon_date', models.CharField(default='May 23 2017', max_length=50)),
                ('sermon_chapter', models.CharField(default='Act 22:1-2', max_length=80)),
                ('sermon_link', models.TextField(default='www.youtube.com')),
                ('sermon_share_code', models.CharField(default='LHJowUFSKMA', max_length=80)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('sermon_day', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.SermonDay')),
                ('sermon_thumbnail_image', models.ForeignKey(help_text='Sermon Thumbnail Image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LordDayMorningSermonField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('hero_title', models.CharField(default='주일 설교 영상', max_length=80)),
                ('hero_subtitle', models.TextField(default='성경을 성경으로 해석한다')),
                ('hero_description', wagtail.core.fields.RichTextField(default='Description')),
                ('sermon_main_title_1', models.CharField(default='최신 주일 예배 설교 영상', max_length=100)),
                ('sermon_main_title_2', models.CharField(default='지난 주일 예배 설교 영상들', max_length=100)),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LordDayMorningSermonPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='PhilippiansSermon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sermon_title', models.TextField(default='Sermon Title')),
                ('sermon_date', models.CharField(default='May 23 2017', max_length=50)),
                ('sermon_chapter', models.CharField(default='Act 22:1-2', max_length=80)),
                ('sermon_link', models.TextField(default='www.youtube.com')),
                ('sermon_share_code', models.CharField(default='LHJowUFSKMA', max_length=80)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('sermon_day', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.SermonDay')),
                ('sermon_thumbnail_image', models.ForeignKey(help_text='Sermon Thumbnail Image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PsamsSermon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sermon_title', models.TextField(default='Sermon Title')),
                ('sermon_date', models.CharField(default='May 23 2017', max_length=50)),
                ('sermon_chapter', models.CharField(default='Act 22:1-2', max_length=80)),
                ('sermon_link', models.TextField(default='www.youtube.com')),
                ('sermon_share_code', models.CharField(default='LHJowUFSKMA', max_length=80)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('sermon_day', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.SermonDay')),
                ('sermon_thumbnail_image', models.ForeignKey(help_text='Sermon Thumbnail Image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RevelationSermon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sermon_title', models.TextField(default='Sermon Title')),
                ('sermon_date', models.CharField(default='May 23 2017', max_length=50)),
                ('sermon_chapter', models.CharField(default='Act 22:1-2', max_length=80)),
                ('sermon_link', models.TextField(default='www.youtube.com')),
                ('sermon_share_code', models.CharField(default='LHJowUFSKMA', max_length=80)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('sermon_day', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.SermonDay')),
                ('sermon_thumbnail_image', models.ForeignKey(help_text='Sermon Thumbnail Image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RomansSermon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sermon_title', models.TextField(default='Sermon Title')),
                ('sermon_date', models.CharField(default='May 23 2017', max_length=50)),
                ('sermon_chapter', models.CharField(default='Act 22:1-2', max_length=80)),
                ('sermon_link', models.TextField(default='www.youtube.com')),
                ('sermon_share_code', models.CharField(default='LHJowUFSKMA', max_length=80)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('sermon_day', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.SermonDay')),
                ('sermon_thumbnail_image', models.ForeignKey(help_text='Sermon Thumbnail Image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='fridaysermon',
            name='sermon_day',
        ),
        migrations.RemoveField(
            model_name='fridaysermon',
            name='sermon_thumbnail_image',
        ),
        migrations.RemoveField(
            model_name='lorddaysermon',
            name='sermon_day',
        ),
        migrations.RemoveField(
            model_name='lorddaysermon',
            name='sermon_thumbnail_image',
        ),
        migrations.RemoveField(
            model_name='lorddaysermonpage',
            name='sermon_hero_description',
        ),
        migrations.RemoveField(
            model_name='lorddaysermonpage',
            name='sermon_hero_subtitle',
        ),
        migrations.RemoveField(
            model_name='lorddaysermonpage',
            name='sermon_hero_title',
        ),
        migrations.RemoveField(
            model_name='lorddaysermonpage',
            name='sermon_main_title_1',
        ),
        migrations.RemoveField(
            model_name='lorddaysermonpage',
            name='sermon_main_title_2',
        ),
        migrations.DeleteModel(
            name='FridaySermon',
        ),
        migrations.DeleteModel(
            name='LordDaySermon',
        ),
        migrations.AddField(
            model_name='lorddaymorningsermonfield',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='sermon_page_fields', to='home.LordDayMorningSermonPage'),
        ),
        migrations.AddField(
            model_name='lorddayafternoonsermonfield',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='sermon_page_fields', to='home.LordDayAfternoonSermonPage'),
        ),
    ]
