# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-07 22:02
from __future__ import unicode_literals

from django.db import migrations, models
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0047_auto_20170707_2120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lorddayafternoonsermonfield',
            name='page',
        ),
        migrations.RemoveField(
            model_name='lorddaymorningsermonfield',
            name='page',
        ),
        migrations.AddField(
            model_name='lorddayafternoonsermonpage',
            name='hero_description',
            field=wagtail.wagtailcore.fields.RichTextField(default='Description'),
        ),
        migrations.AddField(
            model_name='lorddayafternoonsermonpage',
            name='hero_subtitle',
            field=models.TextField(default='성경을 성경으로 해석한다'),
        ),
        migrations.AddField(
            model_name='lorddayafternoonsermonpage',
            name='hero_title',
            field=models.CharField(default='주일 설교 영상', max_length=80),
        ),
        migrations.AddField(
            model_name='lorddayafternoonsermonpage',
            name='sermon_main_title_1',
            field=models.CharField(default='최신 주일 예배 설교 영상', max_length=100),
        ),
        migrations.AddField(
            model_name='lorddayafternoonsermonpage',
            name='sermon_main_title_2',
            field=models.CharField(default='지난 주일 예배 설교 영상들', max_length=100),
        ),
        migrations.AddField(
            model_name='lorddaymorningsermonpage',
            name='hero_description',
            field=wagtail.wagtailcore.fields.RichTextField(default='Description'),
        ),
        migrations.AddField(
            model_name='lorddaymorningsermonpage',
            name='hero_subtitle',
            field=models.TextField(default='성경을 성경으로 해석한다'),
        ),
        migrations.AddField(
            model_name='lorddaymorningsermonpage',
            name='hero_title',
            field=models.CharField(default='주일 설교 영상', max_length=80),
        ),
        migrations.AddField(
            model_name='lorddaymorningsermonpage',
            name='sermon_main_title_1',
            field=models.CharField(default='최신 주일 예배 설교 영상', max_length=100),
        ),
        migrations.AddField(
            model_name='lorddaymorningsermonpage',
            name='sermon_main_title_2',
            field=models.CharField(default='지난 주일 예배 설교 영상들', max_length=100),
        ),
        migrations.DeleteModel(
            name='LordDayAfternoonSermonField',
        ),
        migrations.DeleteModel(
            name='LordDayMorningSermonField',
        ),
    ]
