# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-10 19:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailforms', '0003_capitalizeverbose'),
        ('wagtailredirects', '0005_capitalizeverbose'),
        ('wagtailcore', '0039_collectionviewrestriction'),
        ('home', '0048_auto_20170707_2202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lorddaysermonpage',
            name='page_ptr',
        ),
        migrations.DeleteModel(
            name='LordDaySermonPage',
        ),
    ]
