# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-10 20:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0049_auto_20170710_1942'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PsamsSermon',
            new_name='PsalmsSermon',
        ),
    ]
