# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-10 22:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0019_delete_filter'),
        ('home', '0051_auto_20170710_2049'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empage',
            old_name='em_tab_content',
            new_name='em_tab_content_1',
        ),
        migrations.RenameField(
            model_name='empage',
            old_name='em_tab_content_info',
            new_name='em_tab_content_mission',
        ),
        migrations.RenameField(
            model_name='empage',
            old_name='em_tab_content_age',
            new_name='em_tab_content_pastor',
        ),
        migrations.AddField(
            model_name='empage',
            name='em_tab_content_2',
            field=wagtail.wagtailcore.fields.RichTextField(default='Intro to English Ministry'),
        ),
        migrations.AddField(
            model_name='empage',
            name='em_tab_content_pastor_2',
            field=models.TextField(default='예배 안내: 오후 1:00 청년부실'),
        ),
        migrations.AddField(
            model_name='empage',
            name='em_tab_content_title_2',
            field=models.CharField(default='English Ministry', max_length=30),
        ),
        migrations.AddField(
            model_name='empage',
            name='em_tab_content_vision',
            field=models.CharField(default='English Ministry.', max_length=50),
        ),
        migrations.AddField(
            model_name='empage',
            name='em_tab_image_4',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='empage',
            name='em_tab_image_5',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='empage',
            name='em_tab_image_6',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='empage',
            name='em_tab_title_1',
            field=models.CharField(default='English Ministry', max_length=100),
        ),
        migrations.AddField(
            model_name='empage',
            name='em_tab_title_2',
            field=models.CharField(default='Pastor & Staffs', max_length=100),
        ),
    ]
