# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-10 22:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0052_auto_20170710_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empage',
            name='em_tab_content_pastor',
            field=models.TextField(default='English Ministry.'),
        ),
        migrations.AlterField(
            model_name='empage',
            name='em_tab_content_title_1',
            field=models.TextField(default='English Ministry'),
        ),
        migrations.AlterField(
            model_name='empage',
            name='em_tab_content_title_2',
            field=models.TextField(default='English Ministry'),
        ),
        migrations.AlterField(
            model_name='empage',
            name='em_tab_content_vision',
            field=models.TextField(default='English Ministry.'),
        ),
    ]
