# Generated by Django 2.0.7 on 2018-07-16 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0054_auto_20180710_0219'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lorddayafternoonsermon',
            options={'ordering': ('-service_date',)},
        ),
        migrations.AlterModelOptions(
            name='lorddaymorningsermon',
            options={'ordering': ('-service_date',)},
        ),
        migrations.AlterModelOptions(
            name='philippianssermon',
            options={'ordering': ('-service_date',)},
        ),
        migrations.AlterModelOptions(
            name='psalmssermon',
            options={'ordering': ('-service_date',)},
        ),
        migrations.AlterModelOptions(
            name='revelationsermon',
            options={'ordering': ('-service_date',)},
        ),
        migrations.AlterModelOptions(
            name='romanssermon',
            options={'ordering': ('-service_date',)},
        ),
    ]
